Repository Terminalfreaks/TermTalk-Server, pull requests merged in 2020-06, with the labels that each got.

#3 Add session ids
  index.js
  src/Session.js
  src/Utils.js
Labels: enhancement

#22 update little things
  index.js
  src/functions/loadHistory.js
Labels: bug, enhancement

#24 Save id in sessions
  index.js
  src/commands/chatlock.js
  src/commands/help.js
  src/commands/reload.js
  src/commands/uptime.js
Labels: documentation, enhancement

#25 Server pinging and server list back ends
  config.json
  index.js
  making_a_public_server.md
  package.json
  src/functions/loadHistory.js
Labels: documentation, enhancement

#31 Something required for the server list
  index.js
Labels: enhancement
